Update vendored catch and doctest dependencies
The existing versions caused builds to fail on newer glibc versions,
which changed the internal representation of some constant-looking
symbols to not be constexpr (namely MINSIGSTKSZ):

    /home/aaron/Source/q/infra/include/infra/catch.hpp:10453:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
    10453 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;

See cycfi/q#46 for an example.